spring:
  application:
    name: Cardless-Integration
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
server:
  address: 10.1.22.176
  port: 8085
tcp:
  server:
    ip: 192.168.20.5
    port: 9234